### ISSUE TITLE
Django 1.10 support 

### ISSUE THREAD

**Issue by m-sanders** [MatthewWilkes/django-dob-widget#2]
I have submitted a PR #1  to add Django 1.10 support to Tox and I have had to fix some of the tests.

**Comment by MatthewWilkes** [comment]
Thanks, I've merged this.

**Comment by MatthewWilkes** [comment]
@m-sanders Um, wow. I'm really sorry, I just noticed that I failed to make a release with this fix in it. It's on PyPI now as 1.2.0, although I doubt it's still relevant!
